### ISSUE TITLE
Optionally disable Embedded Tomcat from starting

### ISSUE THREAD

**Issue by rajdavies** [funktionio/funktion-connectors#12]
For some cases, where you are creating a non REST based funktion, it would be nice not to have embedded Tomcat start. Pondering best way to disable - property maybe ?

**Comment by jstrachan** [comment]
Agreed.

I think excluding the `<artifactId>spring-boot-starter-web</artifactId>` should be enough in the pom.xml. FWIW to fix https://github.com/fabric8io/funktion/issues/10 I recently switched from tomcat -> jetty so we could use the same servlet engine for camel http and the `spring-boot-starter-web`.

The only downside of disabling web is we lose actuator and health REST access. Longer term maybe the jolokia agent could detect those and expose them over HTTP? Until then its probably easier to keep the `spring-boot-starter-web` dependency; even if its just used for metrics & health checks.

**Comment by davsclaus** [comment]
Yeah IMHO its good to standardize on /health over HTTP for health checks. I suspect its a tad to complicated to disable HTTP and then use something else as health check?

**Comment by jstrachan** [comment]
yeah - we currently tend to use jetty; though could use undertow instead to reduce the foot print a bit? We need a servlet engine for health checks though - plus for doing `mvn fabric8:watch-spring-boot` so its very handy!

**Comment by davsclaus** [comment]
Yeah I have switched funktion to use undertow

**Comment by davsclaus** [comment]
undertow should be fine
